runtime: go
api_version: go1
application: thegoapp
version: 1

handlers:  

- url: /ws/.*
  script: _go_app

- url: /favicon\.ico 
  mime_type: image/ico 
  static_files: public/favicon.ico 
  upload: public/favicon\.gif 