runtime: go
api_version: go1
application: itaskapp
version: 1

handlers:  

- url: /ws/.*
  script: _go_app
  
- url: /files/.*
  script: _go_app
  
- url: /
  script: _go_app
  
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /code
  static_dir: static/code
   

  

  
- url: /favicon\.ico 
  mime_type: image/ico 
  static_files: public/favicon.ico 
  upload: public/favicon\.gif 